<?php

use Illuminate\Database\Seeder;
use App\Habitacione;

class HabitacioneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $records = [
            [
                'id' => 1,
                'cat_id' => 1,
                'level_id' => 5,
                'nombre' => '42',
                'estado' => 'Activa',
                'status' => 'Ocupada',
            ],
            [
                'id' => 2,
                'cat_id' => 1,
                'level_id' => 5,
                'nombre' => '43',
                'estado' => 'Activa',
                'status' => 'Limpieza',
            ],
            [
                'id' => 3,
                'cat_id' => 1,
                'level_id' => 5,
                'nombre' => '44',
                'estado' => 'Activa',
                'status' => 'Disponible',
            ],
            [
                'id' => 4,
                'cat_id' => 1,
                'level_id' => 5,
                'nombre' => '45',
                'estado' => 'Activa',
                'status' => 'Disponible',
            ],
            [
                'id' => 5,
                'cat_id' => 1,
                'level_id' => 5,
                'nombre' => '46',
                'estado' => 'Activa',
                'status' => 'Disponible',
            ],
            [
                'id' => 6,
                'cat_id' => 1,
                'level_id' => 5,
                'nombre' => '47',
                'estado' => 'Activa',
                'status' => 'Disponible',
            ],
            [
                'id' => 7,
                'cat_id' => 2,
                'level_id' => 1,
                'nombre' => '1',
                'estado' => 'Activa',
                'status' => 'Disponible',
            ],
            [
                'id' => 8,
                'cat_id' => 2,
                'level_id' => 1,
                'nombre' => '2',
                'estado' => 'Activa',
                'status' => 'Disponible',
            ],
            [
                'id' => 9,
                'cat_id' => 2,
                'level_id' => 1,
                'nombre' => '3',
                'estado' => 'Activa',
                'status' => 'Disponible',
            ],
            [
                'id' => 10,
                'cat_id' => 2,
                'level_id' => 1,
                'nombre' => '4',
                'estado' => 'Activa',
                'status' => 'Disponible',
            ],
            [
                'id' => 11,
                'cat_id' => 2,
                'level_id' => 1,
                'nombre' => '5',
                'estado' => 'Activa',
                'status' => 'Ocupada',
            ],
            [
                'id' => 12,
                'cat_id' => 2,
                'level_id' => 1,
                'nombre' => '9',
                'estado' => 'Activa',
                'status' => 'Ocupada',
            ],
            [
                'id' => 13,
                'cat_id' => 2,
                'level_id' => 1,
                'nombre' => '10',
                'estado' => 'Activa',
                'status' => 'Limpieza',
            ],
            [
                'id' => 14,
                'cat_id' => 2,
                'level_id' => 1,
                'nombre' => '11',
                'estado' => 'Activa',
                'status' => 'Limpieza',
            ],
            [
                'id' => 15,
                'cat_id' => 2,
                'level_id' => 1,
                'nombre' => '12',
                'estado' => 'Activa',
                'status' => 'Disponible',
            ],
            [
                'id' => 16,
                'cat_id' => 2,
                'level_id' => 1,
                'nombre' => '13',
                'estado' => 'Activa',
                'status' => 'Limpieza',
            ],
            [
                'id' => 17,
                'cat_id' => 4,
                'level_id' => 4,
                'nombre' => '14',
                'estado' => 'Activa',
                'status' => 'Limpieza',
            ],
            [
                'id' => 18,
                'cat_id' => 4,
                'level_id' => 4,
                'nombre' => '15',
                'estado' => 'Activa',
                'status' => 'Ocupada',
            ],
            [
                'id' => 19,
                'cat_id' => 4,
                'level_id' => 4,
                'nombre' => '16',
                'estado' => 'Activa',
                'status' => 'Limpieza',
            ],
            [
                'id' => 20,
                'cat_id' => 4,
                'level_id' => 4,
                'nombre' => '17',
                'estado' => 'Activa',
                'status' => 'Ocupada',
            ],
            [
                'id' => 21,
                'cat_id' => 4,
                'level_id' => 4,
                'nombre' => '18',
                'estado' => 'Activa',
                'status' => 'Limpieza',
            ],
            [
                'id' => 22,
                'cat_id' => 4,
                'level_id' => 4,
                'nombre' => '19',
                'estado' => 'Activa',
                'status' => 'Ocupada',
            ],
            [
                'id' => 23,
                'cat_id' => 4,
                'level_id' => 4,
                'nombre' => '20',
                'estado' => 'Activa',
                'status' => 'Limpieza',
            ],
            [
                'id' => 24,
                'cat_id' => 4,
                'level_id' => 4,
                'nombre' => '21',
                'estado' => 'Activa',
                'status' => 'Limpieza',
            ],
            [
                'id' => 25,
                'cat_id' => 5,
                'level_id' => 3,
                'nombre' => '22',
                'estado' => 'Activa',
                'status' => 'Ocupada',
            ],
            [
                'id' => 26,
                'cat_id' => 5,
                'level_id' => 3,
                'nombre' => '23',
                'estado' => 'Activa',
                'status' => 'Limpieza',
            ],
            [
                'id' => 27,
                'cat_id' => 5,
                'level_id' => 3,
                'nombre' => '24',
                'estado' => 'Activa',
                'status' => 'Limpieza',
            ],
            [
                'id' => 28,
                'cat_id' => 5,
                'level_id' => 3,
                'nombre' => '25',
                'estado' => 'Activa',
                'status' => 'Ocupada',
            ],
            [
                'id' => 29,
                'cat_id' => 5,
                'level_id' => 3,
                'nombre' => '26',
                'estado' => 'Activa',
                'status' => 'Ocupada',
            ],
            [
                'id' => 31,
                'cat_id' => 5,
                'level_id' => 3,
                'nombre' => '27',
                'estado' => 'Activa',
                'status' => 'Limpieza',
            ],
            [
                'id' => 32,
                'cat_id' => 5,
                'level_id' => 3,
                'nombre' => '28',
                'estado' => 'Activa',
                'status' => 'Limpieza',
            ],
            [
                'id' => 33,
                'cat_id' => 5,
                'level_id' => 2,
                'nombre' => '29',
                'estado' => 'Activa',
                'status' => 'Ocupada',
            ],
            [
                'id' => 34,
                'cat_id' => 7,
                'level_id' => 2,
                'nombre' => '32',
                'estado' => 'Activa',
                'status' => 'Ocupada',
            ],
            [
                'id' => 35,
                'cat_id' => 7,
                'level_id' => 2,
                'nombre' => '33',
                'estado' => 'Activa',
                'status' => 'Disponible',
            ],
            [
                'id' => 36,
                'cat_id' => 5,
                'level_id' => 2,
                'nombre' => '35',
                'estado' => 'Activa',
                'status' => 'Ocupada',
            ],
            [
                'id' => 37,
                'cat_id' => 5,
                'level_id' => 2,
                'nombre' => '36',
                'estado' => 'Activa',
                'status' => 'Disponible',
            ],
            [
                'id' => 38,
                'cat_id' => 7,
                'level_id' => 2,
                'nombre' => '38',
                'estado' => 'Activa',
                'status' => 'Limpieza',
            ],
            [
                'id' => 39,
                'cat_id' => 5,
                'level_id' => 2,
                'nombre' => '39',
                'estado' => 'Activa',
                'status' => 'Disponible',
            ],
            [
                'id' => 40,
                'cat_id' => 5,
                'level_id' => 2,
                'nombre' => '41',
                'estado' => 'Activa',
                'status' => 'Disponible',
            ],
            [
                'id' => 41,
                'cat_id' => 6,
                'level_id' => 2,
                'nombre' => '30',
                'estado' => 'Activa',
                'status' => 'Disponible',
            ],
            [
                'id' => 42,
                'cat_id' => 6,
                'level_id' => 2,
                'nombre' => '31',
                'estado' => 'Activa',
                'status' => 'Disponible',
            ],
            [
                'id' => 43,
                'cat_id' => 6,
                'level_id' => 2,
                'nombre' => '34',
                'estado' => 'Activa',
                'status' => 'Disponible',
            ],
            [
                'id' => 44,
                'cat_id' => 6,
                'level_id' => 2,
                'nombre' => '37',
                'estado' => 'Activa',
                'status' => 'Disponible',
            ],
            [
                'id' => 45,
                'cat_id' => 6,
                'level_id' => 2,
                'nombre' => '40',
                'estado' => 'Activa',
                'status' => 'Disponible',
            ],
            [
                'id' => 46,
                'cat_id' => 3,
                'level_id' => 1,
                'nombre' => '6',
                'estado' => 'Activa',
                'status' => 'Ocupada',
            ],
            [
                'id' => 47,
                'cat_id' => 3,
                'level_id' => 1,
                'nombre' => '7',
                'estado' => 'Activa',
                'status' => 'Ocupada',
            ],
            [
                'id' => 48,
                'cat_id' => 3,
                'level_id' => 1,
                'nombre' => '8',
                'estado' => 'Activa',
                'status' => 'Limpieza',
            ],
        ];

        foreach ($records as $record) {
            App\Habitacione::updateOrCreate(
                ['id' => $record['id']],
                $record
            );
        }
    }
}
